[package]
name = "tuskiyotake"
version = "0.1.0"
edition = "2024"

[dependencies]
logos = { version = "0.15.1", default-features = false, features = [
    "export_derive",
    "logos-derive",
] }
[features]
std = ["logos/std"]
